### ISSUE TITLE
Speed up build process

### ISSUE THREAD

**Issue by krsna1729** [omec-project/upf-epc#13]
**Is your feature request related to a problem? Please describe.**
Build time is currently high due to grpc compilation from source.

**Describe the solution you'd like**
Explore use of packages or binary downloads.

**Comment by krsna1729** [comment]
This will also help [GithHub Actions](https://github.com/omec-project/upf-epc/commit/75567c23d0e48ed7463f9ce16a70a986afc1ce24/checks?check_suite_id=311776576)

**Comment by krsna1729** [comment]
explored in #22. Need to check again when doing #4. Potentially move to golang? since the issue appears to be only with C++?

**Comment by ajamshed** [comment]
Leaving a comment to keep this issue alive.

**Comment by krsna1729** [comment]
Fixed by #51
