### ISSUE TITLE
How to improve the performance of two-way(uplink/downlink) transmission ?

### ISSUE THREAD

**Issue by nelsondoublechen** [omec-project/upf-epc#158]
I'm facing an issue when testing the performance of UFP :
Performance of one way(UL or DL) is about 2M pps,
but two way(UL and DL) is still 2M pps, not as expected 4M pps.
(Using two DPDK bound NICs for N3 an N6.)

Really appreciate if any further suggestion.  
Thank you in advance !

****
I tried to make the performance of two-way touch 4M pps, but these are not workable :
 (1) Pinning multiple cores
 (2) 2 worker threads 

**(1) Pinning multiple cores :**
  Isolate 4 cores on the same NUMA node, but only one core is 100% loading.

  - At host (/etc/default/grub) :  
         GRUB_CMDLINE_LINUX="isolcpus=2,4,6,8"

  - In script(docker_setup.sh) :  
         # Run bessd
         docker run --name bess -td --restart unless-stopped \
	--cpuset-cpus="2,4,6,8"  --cpus 4 \
                   ...

  After running docker_setup.sh and no UL/DL data,  command "htop" : 100% loading is only one core, not four cores.

**(2) 2 worker threads :**
  There is error when executing docker_setup.sh, if workers=2.

  - In conf/upf.json :
    "": "Number of worker threads. Default: use 1 thread to run both (uplink/downlink) pipelines",
    "workers": 2,

  - Executing docker_setup.sh : 
    Error and stop.

  - Error log :  ([P.S.]  enp3s0f0 : N3 NIC  /  enp3s0f1 : N6 NIC  )
     401 module.cc:224] Mismatch in number of workers for module enp3s0f0Merge min required 1 max allowed 64 attached workers 0
     401 module.cc:224] Mismatch in number of workers for module enp3s0f0SrcEther min required 1 max allowed 64 attached workers 0
     401 module.cc:224] Mismatch in number of workers for module enp3s0f0_measure min required 1 max allowed 64 attached workers 0

     401 module.cc:224] Mismatch in number of workers for module enp3s0f1Merge min required 1 max allowed 64 attached workers 0
     401 module.cc:224] Mismatch in number of workers for module enp3s0f1SrcEther min required 1 max allowed 64 attached workers 0
     401 module.cc:224] Mismatch in number of workers for module enp3s0f1_measure min required 1 max allowed 64 attached workers 0

     401 module.cc:224] Mismatch in number of workers for module postDLQoSCounter min required 1 max allowed 1 attached workers 2
     401 module.cc:229] Violates thread safety, returning fatal error
     401 bessctl.cc:726] Module postDLQoSCounter failed check 2
     401 bessctl.cc:730]  --- FATAL CONSTRAINT FAILURE ---

     401 module.cc:224] Mismatch in number of workers for module postULQoSCounter min required 1 max allowed 1 attached workers 2
     401 module.cc:229] Violates thread safety, returning fatal error
     401 bessctl.cc:726] Module postULQoSCounter failed check 2
     401 bessctl.cc:730]  --- FATAL CONSTRAINT FAILURE ---

     401 module.cc:224] Mismatch in number of workers for module preQoSCounter min required 1 max allowed 1 attached workers 2
     401 module.cc:229] Violates thread safety, returning fatal error
     401 bessctl.cc:726] Module preQoSCounter failed check 2
     401 bessctl.cc:730]  --- FATAL CONSTRAINT FAILURE ---

**Comment by krsna1729** [comment]
@nelsondoublechen thanks for trying upf out. The expectation is we can go upto 2 workers with the current code. Will try it and report back.

**Comment by krsna1729** [comment]
```diff
diff --git a/core/modules/counter.h b/core/modules/counter.h
index dfc3ef8..100ce39 100644
--- a/core/modules/counter.h
+++ b/core/modules/counter.h
@@ -16,7 +16,7 @@ struct SessionStats {
 
 class Counter final : public Module {
  public:
-  Counter() : counters() {}
+  Counter() : counters() { max_allowed_workers_ = Worker::kMaxWorkers; }
 
   static const Commands cmds;
   static const gate_idx_t kNumIGates = 10;
```

Basically this module was not being declared as being multi-thread capable. Even though this patch gets it to work, tread carefully. Thread safety is only now being worked upon.

**Comment by nelsondoublechen** [comment]
@krsna1729     , I  am very grateful for your prompt and helpful  reply.  I will try it.  Thank you a lot !

**Comment by levaitamas** [comment]
Thank you @nelsondoublechen and @krsna1729 for the info! 

I did some microbenchmark with the simulator mode recently, and interestingly I have seen throughput more than doubled:
```
| #workers | dir | throughput        | latency [us]               |
|          |     |       Mpps | Gbps |          avg |  p90 |  p95 |
|----------+-----+------------+------+--------------+------+------|
|        1 | UL  |       1.33 | 1.30 |         14.4 | 14.5 | 14.6 |
|        1 | DL  |       1.33 | 1.95 |         15.4 | 15.5 | 15.6 |
|----------+-----+------------+------+--------------+------+------|
|        2 | UL  |       3.31 | 3.29 |         13.9 | 14.6 | 15.0 |
|        2 | DL  |       3.26 | 4.90 |         13.7 | 15.2 | 15.5 |
```

**Comment by nelsondoublechen** [comment]
Thank you  @krsna1729   
It is workable about the two workers, and the throughput is doubled.
And two cores are 100% loading after executing docker_setup.sh

![image](https://user-images.githubusercontent.com/8984979/96842833-1b38aa80-1480-11eb-87ca-e8f5d359b519.png)
//throughput bps = pps * pkt_size

#workers: 1 => one core for two DPDK bound NICs
  - Setting up port enp3s0f0 on worker 0
  - Setting up port enp3s0f1 on worker 0

#workers: 2 => two cores for two DPDK bound NICs and independent
  - Setting up port enp3s0f0 on worker 0
  - Setting up port enp3s0f1 on worker 1

@levaitamas  Congratulation！ 
And that's really interesting throughput is more than doubled.  
If it is possible that 1.33M pps does not reaching the limit ?

**Comment by krsna1729** [comment]
@nelsondoublechen there might be artifacts of simulation mode (in-memory packet generator) causing more than doubling of tput in @levaitamas' case.
