### ISSUE TITLE
An pdrLookUp support

### ISSUE THREAD

**Issue by III-5GC** [omec-project/upf-epc#172]
**Describe the bug**
Hello, Mr./Mrs, It is great to know this UPF project, we are trying to have an integration test of our 5G core network and your upf, and the UE and gNB are simulated by Spirent as you did.
Most of controll plan signaling are correct as below.
![image](https://user-images.githubusercontent.com/68258397/99949566-374ca600-2db6-11eb-9641-3bcf8417916f.png)
(You could take a look of attach file for detail, [mirror_switch_n2_n3_n6.zip](https://github.com/omec-project/upf-epc/files/5586784/mirror_switch_n2_n3_n6.zip).)
As you can see, UE start sending the icmp ping request to 8.8.8.8 after registration and pdu session establishment are completed, and 8.8.8.8 did reply the icmp packet. 

However, something went wrong while downlink traffic. Since I didn't see the ping reply (gtp icmp) packet, I check the GUI of DPDK-UPF and found out that downlink packet could not match the pdrLookUp table.
<img width="202" alt="擷取" src="https://user-images.githubusercontent.com/68258397/99949550-2f8d0180-2db6-11eb-82f0-cdd6b2f7e4cc.PNG">

**Logs**
Here are some logs that I have been try to figure out what might be wrong.
First, I tcpdumped the input port of pdrLookUp function, I would like make sure that contexts of icmp reply packet are correct :
![image](https://user-images.githubusercontent.com/68258397/100034729-cbab1d00-2e37-11eb-970c-b649d3ff67b5.png)
(You could take a look of attach file for detail, [beforePdrLookUp.zip](https://github.com/omec-project/upf-epc/files/5586796/beforePdrLookUp.zip) )

and I also tcpdumped the both output port 1 and 2 of pdrLookUp function, it looks like this:
Output port 1 of pdrLookUP (correct, uplink and decap):
![image](https://user-images.githubusercontent.com/68258397/100035098-5b50cb80-2e38-11eb-8535-9775b0e1a46d.png)
(You could take a look of attach file for detail, [afterPdrLookUpPort1.zip](https://github.com/omec-project/upf-epc/files/5586810/afterPdrLookUpPort1.zip).)

Output port 2 of pdrLookUP (mismatch, downlink and encap):
![image](https://user-images.githubusercontent.com/68258397/100035211-9a7f1c80-2e38-11eb-9712-9d48c84a6288.png)
(You could take a look of attach file for detail, [afterPdrLookUpPort2.zip](https://github.com/omec-project/upf-epc/files/5586818/afterPdrLookUpPort2.zip).)
However, I could not see any abnormal contexts.
Hence I check the log of bess-pfcpiface if the packet shall match PDR and FAR rule.
![image](https://user-images.githubusercontent.com/68258397/100035555-7839ce80-2e39-11eb-934d-d056859152de.png)
(here is the detail logs of bess-pfcpifcae,[bess-pfcpiface.zip](https://github.com/omec-project/upf-epc/files/5586899/bess-pfcpiface.zip).)
For downlink traffic, please correct me if I make any mistake, since the dst IP of the reply packet is 10.10.0.4 and mask is 255.255.255.255 (unique IP), it shall hit the second PDR rule only. I think perhaps something went wrong here but I could not dig deeper into this bug.
Really appreciate if you could share any further suggestion or method to debug.
Thank you in advance !

**Additional context**
Once if the reply packets did match the second rule of pdrLookUp table,  I think it shall goes to hit the FAR ID2 rule next, and will be encapsulated to a gtp packet, that from 192.168.53.81:2152 (DEC 3232249169, N3 of omec-UPF) goes to 192.168.7.227:2152 (DEC 3232237539, N3 of spirent gNB), and the TEID is 33 (DEC 51).
![image](https://user-images.githubusercontent.com/68258397/100035601-8f78bc00-2e39-11eb-83b3-3aaea2caaa7b.png)
![image](https://user-images.githubusercontent.com/68258397/100039554-67d92200-2e40-11eb-89a9-1ba725664116.png)
(Here are the details packets between smf and upf, [smfInPod.zip](https://github.com/omec-project/upf-epc/files/5587050/smfInPod.zip).)

**An Implied question report**
![image](https://user-images.githubusercontent.com/68258397/100044037-94de0280-2e49-11eb-896b-7977592b1782.png)
![image](https://user-images.githubusercontent.com/68258397/100044101-c525a100-2e49-11eb-87c3-5c28c0bf18c8.png)
I noticed that even though the wireshark shows the F-SEID is 0xe5063cf3e1c0b8d3, pfcpiface log gave a fseID 3787503827, which is just 4 bytes, 0xe1c0b8d3.  I dont know if this should be a problem.

**Comment by III-5GC** [comment]
It may not be a bug, please help on removing the tag. Thanks so much.

**Comment by krsna1729** [comment]
@III-5GC sorry missed the notification on this issue. Can you paste the graph starting from input (top) till pktparse?

**Comment by krsna1729** [comment]
regarding uint64 -> uint32 yes this is wrong. thanks for pointing out. we should make it consistent in slowpath and fastpath.

**Comment by krsna1729** [comment]
you can put Dump module after port 2
https://github.com/NetSys/bess/wiki/Built-In-Modules-and-Ports#dump

https://github.com/omec-project/upf-epc/blob/10e82a3ca77e587d6a470bbf182b3a2fccc4e79b/conf/up4.bess#L215

will become

`pdrLookup:pdrFailGate -> Dump(interval=0.25) -> pdrLookupFail::Sink() `

Then you can paste the bess container log to look at the metadata. Also paste the output of 
`docker exec bess ./bessctl show module`

**Comment by tcnieh** [comment]
@krsna1729 Thanks and sorry for late reply. I follow your hints and reproduce the issue.
Since each logs contain 400 lines messages, I upload the log files for clean forum.
Here is the logs of `bessctl show module`
[2020-1208_bess_module.log](https://github.com/omec-project/upf-epc/files/5658698/2020-1208_bess_module.log)

Here is the logs of bess container
[2020-1208_bess_logs.log](https://github.com/omec-project/upf-epc/files/5658692/2020-1208_bess_logs.log)

In case, I also dump the pcap of pdrlookup port 2 again
[2020-1208_BESS_DL_dump0_pdrLookupFail.zip](https://github.com/omec-project/upf-epc/files/5658724/2020-1208_BESS_DL_dump0_pdrLookupFail.zip)

I take a quickly check of both pcap file and logs of bess container, basically the contain of dump data is as same as pcap file.
For Metadata buffer, I can only identify the `0A 0A 00 05 08 08 08 08`, which i think it is 10.10.0.5 and 8.8.8.8. 
![image](https://user-images.githubusercontent.com/32285674/101475474-6bfc5800-3987-11eb-8cdf-9a2a986b3e69.png)

I hope I give you enough information, thanks again.

**Comment by krsna1729** [comment]
@tcnieh @III-5GC 

```
  pdrLookup::WildcardMatch(8 fields, 2 rules)
    Per-packet metadata fields:
      src_iface: read   1 bytes at offset 20
tunnel_ipv4_dst: read   4 bytes at offset 24
           teid: read   4 bytes at offset 28
         src_ip: read   4 bytes at offset 40
         dst_ip: read   4 bytes at offset 36
       src_port: read   2 bytes at offset 32
       dst_port: read   2 bytes at offset 22
       ip_proto: read   1 bytes at offset 21
         pdr_id: write  4 bytes (no downstream reader)
          fseid: write  4 bytes at offset 8
         ctr_id: write  4 bytes at offset 12
         far_id: write  4 bytes at offset 16
```

So this says src_iface is at offset 20
```
      src_iface: read   1 bytes at offset 20
```

Contents of metadata
```
Metadata buffer at [0x22565ad580], len=128
00000000: C8 6D 39 26 D8 22 06 00 00 00 00 00 00 00 00 00 | .m9&."..........
00000010: 00 00 00 00 01 01 FF FF FF FF FF FF FF FF FF FF | ................
00000020: FF FF 00 00 0A 0A 00 05 08 08 08 08 00 00 00 00 | ................
00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
```

At offset 20 the 1 byte value is `01` which should be `02` like the PDR log said. This is why the match is failing. Can you paste the top portion of graph GUI before pktParse? This can help identify the problem why it gets src_iface as 01. My guess is the downlink traffic is being routed to the same interface as uplink traffic.

**Comment by tcnieh** [comment]
Sorry for late reply, here is a total graph GUI.
![image](https://user-images.githubusercontent.com/32285674/101738425-1946ab80-3b01-11eb-9524-48b18938b9a3.png)
![image](https://user-images.githubusercontent.com/32285674/101738624-66c31880-3b01-11eb-83de-b6de4cbb6830.png)
![image](https://user-images.githubusercontent.com/32285674/101739048-f7015d80-3b01-11eb-89a5-9e824f342ef0.png)
![image](https://user-images.githubusercontent.com/32285674/101739137-15ffef80-3b02-11eb-8461-a9f1ce6b43d7.png)

Please have a look.

**Comment by krsna1729** [comment]
@tcnieh oh boy with NAT :P can we repeat without NAT if possible? Also add another dump after setattr0 in the above pic

https://github.com/omec-project/upf-epc/blob/c98b3c31270bbe34c7ced0327089c462cacd8bae/conf/up4.bess#L268-L270

will become 

```
 _in:gate \ 
     -> SetMetadata(attrs=[{'name':'src_iface', 'size':1, 'value_int':Core}]) \
     -> attrdump::Dump(interval=0.25) \
     -> linkMerge # Start of the shared pipeline 
```

**Comment by krsna1729** [comment]
@tcnieh can you join https://onf-community.slack.com/ ?

**Comment by tcnieh** [comment]
@krsna1729 Yes,yes, thanks for your reply, I join the slack. Look forward to your reply when you are available.

**Comment by krsna1729** [comment]
local diff of up4.bess cause of the issue

```
Access = 1
Core = 1
```

instead of 

```
Access = 1
Core = 2
```
