### ISSUE TITLE
upf updates the action parameter in FAR to forwardU or ForwardD.

### ISSUE THREAD

**Issue by badhrinathpa** [omec-project/upf-epc#192]
**Describe the bug**
Bess UPF updates the action parameter in FAR to forwardU or ForwardD.

**To Reproduce**
Basic attach test case

**Expected behavior**
Set value of action as per spec (notifyCP, buffer, drop, forward).

**Logs**

**Additional context**

**Comment by krsna1729** [comment]
@badhrinathpa this is done right?
