### ISSUE TITLE
Mirror veth interface: enp63s0f0 misconfigured

### ISSUE THREAD

**Issue by jiaway4892** [omec-project/upf-epc#199]
Hello, Mr./Mrs, I am trying to deploy dpdk upf on the docker. However, after running "run up4" command, I found that vdev interface for mirror link cannot be attached. The error logs is shown below. The "show port" result show that only two port are created. How could I solve this problem? Thanks!

![image](https://user-images.githubusercontent.com/29172295/105336047-ba05ac00-5c13-11eb-8e2b-6f15ff162de9.png)

`cat /tmp/bessd.INFO`

> I0121 09:47:14.218289   640 pmd.cc:268] Initializing Port:0 with memory from socket 0
I0121 09:47:14.295985   640 pmd.cc:268] Initializing Port:1 with memory from socket 0
I0121 09:47:14.431156   640 pmd.cc:268] Initializing Port:0 with memory from socket 0
I0121 09:47:14.501525   640 dpdk.cc:72] rte_pmd_init_internals(): net_af_packet0: could not set PACKETASS on AF_PACKET socket for enp63s0f0-vdev:Protocol not available
I0121 09:47:14.506814   640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.506852   640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.514791   640 dpdk.cc:72] EAL: Driver cannot attach the device (net_af_packet0)
I0121 09:47:14.514803   640 dpdk.cc:72] EAL: Failed to attach device on primary process
I0121 09:47:14.660923   640 pmd.cc:268] Initializing Port:1 with memory from socket 0
I0121 09:47:14.732236   640 dpdk.cc:72] rte_pmd_init_internals(): net_af_packet1: could not set PACKETASS on AF_PACKET socket for enp63s0f1-vdev:Protocol not available
I0121 09:47:14.743819   640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.743860   640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.759796   640 dpdk.cc:72] EAL: Driver cannot attach the device (net_af_packet1)
I0121 09:47:14.759846   640 dpdk.cc:72] EAL: Failed to attach device on primary process

**Comment by krsna1729** [comment]
Hi @jiaway4892! Can you please paste output of `ip addr show` inside the bess container?

**Comment by jiaway4892** [comment]
Hi @krsna1729 ~ Thanks for your reply!
This is output of `ip addr show`
![ip_addr_show](https://user-images.githubusercontent.com/29172295/105390774-5c458400-5c54-11eb-8c9c-17fcf4701d38.PNG)

I think the mac & ip address of the interface is correct.

**Comment by krsna1729** [comment]
```
I0121 09:47:14.501525 640 dpdk.cc:72] rte_pmd_init_internals(): net_af_packet0: could not set PACKETASS on AF_PACKET socket for enp63s0f0-vdev:Protocol not available
I0121 09:47:14.506814 640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.506852 640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.514791 640 dpdk.cc:72] EAL: Driver cannot attach the device (net_af_packet0)
I0121 09:47:14.514803 640 dpdk.cc:72] EAL: Failed to attach device on primary process
I0121 09:47:14.660923 640 pmd.cc:268] Initializing Port:1 with memory from socket 0
I0121 09:47:14.732236 640 dpdk.cc:72] rte_pmd_init_internals(): net_af_packet1: could not set PACKETASS on AF_PACKET socket for enp63s0f1-vdev:Protocol not available
I0121 09:47:14.743819 640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.743860 640 dpdk.cc:72] EAL: Error: Invalid memory
I0121 09:47:14.759796 640 dpdk.cc:72] EAL: Driver cannot attach the device (net_af_packet1)
I0121 09:47:14.759846 640 dpdk.cc:72] EAL: Failed to attach device on primary process
```

I am not able to find where this error is in dpdk source code. Also Invalid memory is concerning.
```
rte_pmd_init_internals(): net_af_packet0: could not set PACKETASS on AF_PACKET socket for enp63s0f0-vdev:Protocol not available
```

**Comment by III-5GC** [comment]
Dear krsna1729,
Thanks for the hint, after we update the kernel version
It works fine.

**Comment by krsna1729** [comment]
@III-5GC Can you post before/after kernel versions?

**Comment by tcnieh** [comment]
Yes, previous version was 3.10.x by centOS7, version now is 5.4.105, just for your information.
