### ISSUE TITLE
performance Improvement in concurrent Pipeline

### ISSUE THREAD

**Issue by amarsri28** [omec-project/upf-epc#212]
performance Improvement in concurrent Pipeline

**Comment by krsna1729** [comment]
@amarsri28 lets first remove the hardcode and then worry about performance?

**Comment by amarsri28** [comment]
performance improvement already been done. this activity is  for that.
 if  this discussion is about configuring Hash size then it is under implementation .

**Comment by krsna1729** [comment]
Ok if its already done please add more details of the work. performance improvement doesnt convey much

**Comment by amarsri28** [comment]
sure, details will be given while closing activity.

In the meanwhile if its required to change hashtable size locally for any purpose, 
 just search for this string ".entries = 1<<20" / ".entries = 1<<19" in 
"https://github.com/omec-project/upf-epc/blob/master/patches/bess/0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch"    and provide desired size.

this should'nt block development in any case.
