### ISSUE TITLE
[DPDK] Investigate use of FIB library for routing

### ISSUE THREAD

**Issue by krsna1729** [omec-project/upf-epc#24]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
FIB library was added in 19.11. Performance seems of ADD/DELETE seems to be orders of magnitude quicker and lookup is on par. Investigate use of this library for routing.
https://gist.github.com/krsna1729/af44263fa651085696bd0a211c41a231

**Describe alternatives you've considered**
Continue with LPM.

**Comment by ajamshed** [comment]
Linking `dpdk-19.11` to the BESS source is generating compilation issues. Will let you know once compilation issues are resolved.

**Comment by krsna1729** [comment]
Maybe we can take this as the starting point https://github.com/NetSys/bess/pull/943

**Comment by ajamshed** [comment]
Please see #28.

**Comment by ajamshed** [comment]
Closing this issue since the PR has been sent in to the master branch
