### ISSUE TITLE
setting the network namespace "pause" failed: Invalid argument

### ISSUE THREAD

**Issue by mgeiszler** [omec-project/upf-epc#247]
**Describe the bug**
On Ubuntu 20.04 (ubuntu-20.04.2-live-server-amd64.iso) running setup script:
upf-epc$ ./docker_setup
...
${ifaces[$i]}= ens803f2
sudo ip netns exec pause ip link add "${ifaces[$i]}" type veth peer name "${ifaces[$i]}" -vdev
setting the network namespace "pause" failed: Invalid argument

NOTES:
- Before the "link add" command above is run:
`docker run --name pause -td --restart unless-stopped
Unable to find image 'k8s.gcr.io/pause:latest' locally
latest: Pulling from pause
a3ed95caeb02: Pull complete                                                                                         4964c72cd024: Pull complete                                                                                         Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Downloaded newer image for k8s.gcr.io/pause:latest
71f5f5368b031171102d97411b098e5720c23378a6682c384047aa601f4a453f
sandbox=$(docker inspect --format={{.NetworkSettings.SandboxKey}} pause)
sudo ln -s "$sandbox" /var/run/netns/pause
`

**To Reproduce**
1. Setup VM with ubuntu-20.04.2-live-server-amd64.iso

2. https://github.com/omec-project/upf-epc/blob/master/INSTALL.md
./docker_setup.sh

**Expected behavior**

NOTE: The following error stops the processing of the rest of the docker setup script.
setting the network namespace "pause" failed: Invalid argument

**Logs**
Logs with the actual error and context

**Additional context**

`$ ls -l /var/run/netns/pause
lrwxrwxrwx 1 root root 35 Apr  5 14:51 /var/run/netns/pause -> /run/snap.docker/netns/7a96792d4d96
`
` ls -l /run/netns
total 0
lrwxrwxrwx 1 root root 35 Apr  5 14:51 pause -> /run/snap.docker/netns/7a96792d4d96
`
` ls -l /run/snap.docker/netns/7a96792d4d96
-rw-r--r-- 1 root root 0 Apr  5 14:51 /run/snap.docker/netns/7a96792d4d96
`
`$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
upf-epc-pfcpiface   0.3.0-dev           03d5fae8a594        34 minutes ago      24MB
upf-epc-cpiface     0.3.0-dev           cf732878cb43        34 minutes ago      90.4MB
upf-epc-bess        0.3.0-dev           0659ae2bbdd4        35 minutes ago      411MB
k8s.gcr.io/pause    latest              350b164e7ae1        6 years ago         240kB
`
`$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                                      NAMES
71f5f5368b03        k8s.gcr.io/pause    "/pause"            34 minutes ago      Up 34 minutes       0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:10514->10514/tcp   pause
`
`# lsns
        NS TYPE   NPROCS   PID USER             COMMAND
4026531835 cgroup    324     1 root             /sbin/init maybe-ubiquity
4026531836 pid       323     1 root             /sbin/init maybe-ubiquity
4026531837 user      324     1 root             /sbin/init maybe-ubiquity
4026531838 uts       320     1 root             /sbin/init maybe-ubiquity
4026531839 ipc       323     1 root             /sbin/init maybe-ubiquity
4026531840 mnt       310     1 root             /sbin/init maybe-ubiquity
4026531860 mnt         1   105 root             kdevtmpfs
4026531992 net       323     1 root             /sbin/init maybe-ubiquity
4026532535 mnt         1   654 root             /lib/systemd/systemd-udevd
4026532536 uts         1   654 root             /lib/systemd/systemd-udevd
4026532561 mnt         1   861 systemd-timesync /lib/systemd/systemd-timesyncd
4026532562 uts         1   861 systemd-timesync /lib/systemd/systemd-timesyncd
4026532563 mnt         1   922 systemd-network  /lib/systemd/systemd-networkd
4026532564 mnt         1   931 systemd-resolve  /lib/systemd/systemd-resolved
4026532656 mnt         1 45474 root             /pause
4026532657 uts         1 45474 root             /pause
4026532658 ipc         1 45474 root             /pause
4026532659 mnt         6  2237 root             dockerd --group docker --exec-root=/run/snap.docker --data-root=/var/
4026532663 pid         1 45474 root             /pause
4026532701 mnt         1  1144 root             /lib/systemd/systemd-logind
4026532702 mnt         1  1135 root             /usr/sbin/irqbalance --foreground
4026532703 uts         1  1144 root             /lib/systemd/systemd-logind
4026532729 net         1 45474 root             /pause
`
`# lsns | grep mnt
4026531840 mnt       311     1 root             /sbin/init maybe-ubiquity
4026531860 mnt         1   105 root             kdevtmpfs
4026532535 mnt         1   654 root             /lib/systemd/systemd-udevd
4026532561 mnt         1   861 systemd-timesync /lib/systemd/systemd-timesyncd
4026532563 mnt         1   922 systemd-network  /lib/systemd/systemd-networkd
4026532564 mnt         1   931 systemd-resolve  /lib/systemd/systemd-resolved
4026532656 mnt         1 45474 root             /pause
4026532659 mnt         6  2237 root             dockerd --group docker --exec-root=/run/snap.docker --data-root=/var/snap/docker/common/var-lib-docker --pidfile=/run/snap.docker/docker.pid --config-file=/var/snap/docker/796/config/daemon.json
4026532701 mnt         1  1144 root             /lib/systemd/systemd-logind
4026532702 mnt         1  1135 root             /usr/sbin/irqbalance --foreground
`
`# ls -l /proc/mounts
lrwxrwxrwx 1 root root 11 Apr  5 13:43 /proc/mounts -> self/mounts
/proc# ls -l self/mounts
-r--r--r-- 1 root root 0 Apr  5 15:34 self/mounts
`
docker version
`Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 Experimental:      false
`
`Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
`

**Comment by krsna1729** [comment]
Could you try installing docker like this https://get.docker.com/ instead of using snap or older distro based version?

**Comment by krsna1729** [comment]
If possible please markdown format the outputs in your comments

**Comment by mgeiszler** [comment]
docker version
`Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
`
`Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`
NOTE: I was able to get further:
`docker run --name pause -td --restart unless-stopped
Unable to find image 'k8s.gcr.io/pause:latest' locally
latest: Pulling from pause
a3ed95caeb02: Pull complete
4964c72cd024: Pull complete
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Downloaded newer image for k8s.gcr.io/pause:latest
9c426c5abf4c024f0324e5c13dfbd3de9bcc7edb9fcc243968aecac79b93bb8a
sandbox=$(docker inspect --format={{.NetworkSettings.SandboxKey}} pause)
sudo ln -s "$sandbox" /var/run/netns/pause
!!!MG setup_mirror_links
!!!setup_mirror_links: $i= 0
${ifaces[$i]}= ens803f2
sudo ip netns exec pause ip link add "${ifaces[$i]}" type veth peer name "${ifaces[$i]}" -vdev
both "name" and "dev" cannot be used when creating devices.
`

**Comment by mgeiszler** [comment]
Closing issue.  Thanks for tips.
