### ISSUE TITLE
upf-epc docker containers in constant restarting status

### ISSUE THREAD

**Issue by mgeiszler** [omec-project/upf-epc#250]
**Describe the bug**
`$ docker exec bess-pfcpiface pfcpiface -config /conf/upf.json -simulate create
Error response from daemon: Container 7ac699b7cb5bbc10d054b0015bf78a4a12d298f3c3b2ab18ebea310d5b4ca2ac is restarting, wait until the container is running
`

**To Reproduce**
`Make changes for sim mode.`
`DOCKER_BUILDKIT=0 ./docker_setup.sh`
`docker exec bess-pfcpiface pfcpiface -config /conf/upf.json -simulate create
`
**Expected behavior**
The containers should not be in constant restarting status:
`$ docker ps -a`
`CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                          PORTS                                                                                                  NAMES`
`7ac699b7cb5b   upf-epc-pfcpiface:0.3.0-dev   "/bin/pfcpiface -con…"   14 hours ago   Restarting (1) 53 seconds ago                                                                                                          bess-pfcpiface`
`f2667a20e0d9   upf-epc-bess:0.3.0-dev        "bessctl http 0.0.0.…"   14 hours ago   Up 25 minutes                                                                                                                          bess-web`
`489765ae6d37   upf-epc-bess:0.3.0-dev        "bessd -f -grpc-url=…"   14 hours ago   Restarting (1) 49 seconds ago                                                                                                          bess`
`6a84f1041df3   k8s.gcr.io/pause              "/pause"                 14 hours ago   Up 25 minutes                   0.0.0.0:8000->8000/tcp,                             0.0.0.0:8080->8080/tcp, 0.0.0.0:10514->10514/tcp   pause
`

`$ docker ps -a`
`CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                          PORTS                                                                      NAMES`
`7ac699b7cb5b   upf-epc-pfcpiface:0.3.0-dev   "/bin/pfcpiface -con…"   15 hours ago   Restarting (1) 28 seconds ago                                                                              bess-pfcpiface`
`f2667a20e0d9   upf-epc-bess:0.3.0-dev        "bessctl http 0.0.0.…"   15 hours ago   Up 31 minutes                                                                                              bess-web`
`489765ae6d37   upf-epc-bess:0.3.0-dev        "bessd -f -grpc-url=…"   15 hours ago   Restarting (1) 23 seconds ago                                                                              bess`
`6a84f1041df3   k8s.gcr.io/pause              "/pause"                 15 hours ago   Up 31 minutes                   0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:10514->10514/tcp   pause`

**Logs**
Logs with the actual error and context

**Additional context**
`$ docker images`
`REPOSITORY                  TAG          IMAGE ID       CREATED         SIZE`
`upf-epc-pfcpiface           0.3.0-dev    8876bf29c0bd   15 hours ago    24MB`
`<none>                      <none>       5d6ad667bc0b   15 hours ago    968MB`
`<none>                      <none>       c3d446cda428   15 hours ago    6.83GB`
`<none>                      <none>       b6337c50f3ac   15 hours ago    895MB`
`upf-epc-cpiface             0.3.0-dev    69f0fc5a163e   15 hours ago    90.4MB`
`<none>                      <none>       ef48a5672195   15 hours ago    1.03GB`
`upf-epc-bess                0.3.0-dev    0393a2968fff   15 hours ago    501MB`
`python                      3.9.3-slim   2fa94649b3f0   4 days ago      114MB`
`golang                      latest       0debfc3e0c9e   5 days ago      862MB`
`alpine                      latest       49f356fa4513   6 days ago      5.61MB`
`ubuntu                      bionic       3339fde08fc3   12 days ago     63.3MB`
`nefelinetworks/bess_build   latest       eb716387e211   11 months ago   887MB`
`k8s.gcr.io/pause            latest       350b164e7ae1   6 years ago     240kB`

**Comment by krsna1729** [comment]
Can you paste the output of 
```
docker logs bess-pfcpiface
docker logs bess
```

**Comment by mgeiszler** [comment]
Issue: According to the bess logs the issue seemed to be caused by the upf-epc-bess image missing files "kmod/bess.ko" and "/sbin/insmod".
Solution: I needed to create a new "upf-epc-bess:0.3.0-dev" image with the missing files.

**Comment by krsna1729** [comment]
@mgeiszler thats a warning not an error. please do post what you did.
