### ISSUE TITLE
Adjustable of log level

### ISSUE THREAD

**Issue by tcnieh** [omec-project/upf-epc#251]
**Is your feature request related to a problem? Please describe.**
This feature request is not quite related to a problem.
Some time, while the UPF data traffic works abnormally, user may like to check the routing table or PFCP inform, such as contains of FAR/PDR. 

Is it possible that the user is able to set the log level of each PFCP, so that we may get the informs like below
![image](https://user-images.githubusercontent.com/32285674/113965910-d1daec80-9860-11eb-8de6-111862e1c562.png)
![image](https://user-images.githubusercontent.com/32285674/113965948-ddc6ae80-9860-11eb-8f0c-489886e62e5b.png)

**Comment by krsna1729** [comment]
https://github.com/omec-project/upf-epc/commit/cc3e0cc59090446046cbfffb3c61ecdc57f2a24a#diff-3b5a77d7038f4ee73fc875209127e3ead9d9f74cbce0b5acfdb1378ae951c9d4

This introduced prints of PDR/FAR. We need to allow this only with levelled logging, else it will flood the logs.
