### ISSUE TITLE
Failure starting the pktgen container

### ISSUE THREAD

**Issue by mgeiszler** [omec-project/upf-epc#253]
**Describe the bug**
`$ docker run --name pktgen -td --restart unless-stopped \`
>            --cpuset-cpus=2-5 --ulimit memlock=-1 --cap-add IPC_LOCK \
>            -v /dev/hugepages:/dev/hugepages -v "$PWD/conf":/opt/bess/bessctl/conf \
>            --device=/dev/vfio/vfio --device=/dev/vfio/176 \
>            upf-epc-bess1mg:"$(<VERSION)" -grpc-url=0.0.0.0:10514
`f9c8bac4c0dcf839dd1664ed29bbce64ffe9b6cee1c5d181277aad284b0df5f3`
`docker: Error response from daemon: error gathering device information while adding custom device "/dev/vfio/176": no such file or directory.
`
**To Reproduce**
Setup sim for pktgen:
`DOCKER_BUILDKIT=0 ./docker_setup.sh'
'docker exec bess-pfcpiface pfcpiface -config /conf/upf.json -simulate create'
`
`docker run --name pktgen -td --restart unless-stopped \
           --cpuset-cpus=2-5 --ulimit memlock=-1 --cap-add IPC_LOCK \
           -v /dev/hugepages:/dev/hugepages -v "$PWD/conf":/opt/bess/bessctl/conf \
           --device=/dev/vfio/vfio --device=/dev/vfio/176 \
           upf-epc-bess1mg:"$(<VERSION)" -grpc-url=0.0.0.0:10514
`

**Expected behavior**
pktgen container should start, so one can start the following command:
`$ docker exec -it pktgen ./bessctl run pktgen`

**Logs**
bess log
`I0409 18:44:15.949054     1 main.cc:62] Launching BESS daemon in process mode...
I0409 18:44:15.949154     1 main.cc:75] bessd unknown
I0409 18:44:15.957208     1 bessd.cc:456] Loading plugin (attempt 1): /bin/modules/sequential_update.so
I0409 18:44:15.972048     1 memory.cc:128] /sys/devices/system/node/possible not available. Assuming a single-node system...
I0409 18:44:15.972066     1 dpdk.cc:167] Initializing DPDK EAL with options: ["bessd", "--master-lcore", "127", "--lcore", "127@9-10", "--no-shconf", "--legacy-mem", "--socket-mem", "1024", "--huge-unlink"]`
`EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
Option --master-lcore is deprecated use main-lcore
EAL: Selected IOVA mode 'PA'`
`EAL: No available hugepages reported in hugepages-1048576kB`
`I0409 18:44:15.977942     1 dpdk.cc:66] EAL: Probing VFIO support...`
`I0409 18:44:16.488131     1 dpdk.cc:66] EAL:   Invalid NUMA socket, default to 0`
`I0409 18:44:16.488155     1 dpdk.cc:66] EAL:   Invalid NUMA socket, default to 0`
`I0409 18:44:16.488279     1 dpdk.cc:66] EAL: No legacy callbacks, legacy socket not created`
`Segment 0-0: IOVA:0x2ab000000, len:2097152, virt:0x100200000, socket_id:0, hugepage_sz:2097152, nchannel:0, nrank:0 fd:8`
`...`
`I0409 18:44:16.489435     1 packet_pool.cc:49] Creating DpdkPacketPool for 262144 packets on node 0
I0409 18:44:16.489444     1 packet_pool.cc:70] PacketPool0 requests for 262144 packets
I0409 18:44:16.541139     1 packet_pool.cc:157] PacketPool0 has been created with 262144 packets
I0409 18:44:16.541249     1 pmd.cc:68] 0 DPDK PMD ports have been recognized:
I0409 18:44:16.541272     1 vport.cc:318] vport: BESS kernel module is not loaded. Loading...
I0409 18:44:16.550199     1 bessctl.cc:1931] Server listening on 0.0.0.0:10514
I0409 18:44:16.551793366       1 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 1, CQ timeout (msec): 1000
I0409 18:44:26.255146    12 bessctl.cc:487] *** All workers have been paused ***
I0409 18:44:26.591234    38 worker.cc:319] Worker 0(0x7f6239bab700) is running on core 9 (socket 0)
I0409 18:44:26.662286    40 bessctl.cc:691] Checking scheduling constraints
I0409 18:44:26.662710    40 bessctl.cc:516] *** Resuming ***
`
bess-pfcpiface log
`...
2021/04/12 13:54:47 messages.go:623: SMF address  172.17.0.1:8805
2021/04/12 13:54:49 conn.go:100: read udp 172.18.0.2:8805: i/o timeout
2021/04/12 13:54:49 messages.go:565: cpConnected :  false msg  false
2021/04/12 13:54:49 messages.go:574: cpConnected  false msg -  false
2021/04/12 13:54:52 messages.go:592: Retry pfcp connection setup  172.17.0.1
2021/04/12 13:54:52 messages.go:555: SPGWC/SMF hostname  172.17.0.1
2021/04/12 13:54:52 messages.go:557: SPGWC/SMF address IP inside manageSmfConnection  172.17.0.1
2021/04/12 13:54:52 messages.go:605: n4DstIp  172.17.0.1
2021/04/12 13:54:52 messages.go:623: SMF address  172.17.0.1:8805
`
**Additional context**
`$ docker ps -a`
`CONTAINER ID   IMAGE                         COMMAND                  CREATED              STATUS      PORTS                                                                      NAMES`
`f9c8bac4c0dc   upf-epc-bess1mg:0.3.0-dev     "bessd -f -grpc-url=…"   About a minute ago   Created                                                                                pktgen`
`9472186c3269   upf-epc-pfcpiface:0.3.0-dev   "/bin/pfcpiface -con…"   2 days ago           Up 2 days                                                                              bess-pfcpiface`
`072a692acdd7   upf-epc-bess1mg:0.3.0-dev     "bessctl http 0.0.0.…"   2 days ago           Up 2 days                                                                              bess-web`
`867a4c42f7f5   upf-epc-bess1mg:0.3.0-dev     "bessd -f -grpc-url=…"   2 days ago           Up 2 days                                                                              bess`
`46157802d793   k8s.gcr.io/pause              "/pause"                 2 days ago           Up 2 days   0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:10514->10514/tcp   pause
`

**Comment by krsna1729** [comment]
error:
```
"/dev/vfio/176": no such file or directory.
```

Please customize the docker commandline as per your setup

```
--device=/dev/vfio/vfio --device=/dev/vfio/176 \
```

If you have setup DPDK compatible interfaces bound to vfio-pci kernel module. you should see them under /dev/vfio/. To learn more about DPDK, binding interfaces etc., please go through DPDK docs https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html#linux-gsg-binding-kernel

**Comment by mgeiszler** [comment]
According to the doc https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html#linux-gsg-binding-kernel, only Ubuntu 20.10 supports VFIO framework. "Linux versions earlier than version 5.7 do not support the creation of virtual functions within the VFIO framework."  
`However the container only has the Ubuntu 18.04 linux version: `
`docker exec 2e824abb4ffd uname -r
4.15.0-140-generic`

**Comment by krsna1729** [comment]
_Since Linux version 5.7, the vfio-pci module supports the creation of virtual functions. After the PF is bound to vfio-pci module, the user can create the VFs using the sysfs interface, and these VFs will be bound to vfio-pci module automatically._

This is only relevant if you have a PF bound to vfio-pci and want to create VFs and use it. Generally this is not the case as the PF is bound to kernel driver and VFs are created, bound to vfio-pci and assigned to containers/VMs.

UPF works on baremetal and VMs. In case of VMs you would need to use vfio in [no iommu mode](https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html#vfio-no-iommu-mode) to be able to bind the device and use. Ideally we run anywhere DPDK can run which is published [here](https://doc.dpdk.org/guides/rel_notes/release_20_11.html#tested-platforms)

What is the setup you are trying this on?

**Comment by krsna1729** [comment]
Were you able to run the upf with interfaces? Its the same requirement for pktgen too.

**Comment by mgeiszler** [comment]
This is the error encountered when using the no iommu mode:
`I0414 17:57:47.159931     1 vport.cc:318] vport: BESS kernel module is not loaded. Loading...^M
insmod: ERROR: could not insert module /bin/kmod/bess.ko: Invalid module format^M
^[[0;33mW0414 17:57:47.162346     1 vport.cc:330] Cannot load kernel module /bin/kmod/bess.ko^M
^[[mI0414 17:57:47.162380     1 bessctl.cc:1931] Server listening on 0.0.0.0:10514^M
`

**Comment by krsna1729** [comment]
Its just a warning. did you run step 5?

```
docker exec -it pktgen ./bessctl run pktgen
```
