### ISSUE TITLE
PFCP sim mode Connection refused

### ISSUE THREAD

**Issue by mgeiszler** [omec-project/upf-epc#256]
**Describe the bug**
Setup configuration for sim mode.  And set the mac address appropriately.
`# DOCKER_BUILDKIT=0 ./docker_setup.sh &>  logs/20210413a_docker_setup.sh_sim_only_w_mac_addrs`
`# docker exec bess-pfcpiface pfcpiface -config /conf/upf.json -pfcpsim`
`2021/04/13 19:18:51 main.go:127: {sim 50000 {ens803f2} {ens803f3} {172.17.0.1  spgwc false 10.250.0.0/16 8080} {172.17.0.1/32 onos 51001 10.250.0.0/24} false {16.0.0.1 11.1.1.129 13.1.1.199 6.6.6.6 9.9.9.9 0x30000000 0x90000000}}`
`2021/04/13 19:18:51 bess.go:249: setUpfInfo bess`
`2021/04/13 19:18:51 bess.go:253: IP pool :  10.250.0.0/16`
`2021/04/13 19:18:51 main.go:114: Access  IP:  198.18.0.1`
`2021/04/13 19:18:51 main.go:114: Core  IP:  198.19.0.1`
`2021/04/13 19:18:51 bess.go:268: Dest address  172.17.0.1`
`2021/04/13 19:18:51 bess.go:270: SPGWU/UPF address IP:  172.18.0.2`
`2021/04/13 19:18:51 bess.go:279: bessIP  localhost:10514`
`2021/04/13 19:18:51 pfcpsim.go:31: sent heartbeat request to: 127.0.0.1:8805`
`2021/04/13 19:18:51 pfcpsim.go:36: read udp 127.0.0.1:44286->127.0.0.1:8805: recvfrom: connection refused`

**To Reproduce**
See above.
gRPC sim mode seems to work. 

**Expected behavior**

**Logs**

**Additional context**
What is the difference the the config setup between "gRPC sim mode" and "PFCP sim mode"  Thanks

**Comment by krsna1729** [comment]
Yes I had come across this recently. Need to look further.

**Comment by krsna1729** [comment]
The difference mainly is that in gRPC mode we do not involve the PFCP layer processing of pfcpiface. Instead we directly craft the internal structures and send over gRPC to be installed in the fastpath tables. In pfcpsim mode we launch a PFCP peer that crafts PFCP messages to pfcpiface, so it goes through the protocol parsing layer. This is limited to functional testing only and can emulate create, modify and delete of a single session.

**Comment by mgeiszler** [comment]
@krsna1729 Any status on the "connection refused"

**Comment by mgeiszler** [comment]
https://github.com/omec-project/upf-epc/pull/259 is not fixed nor merged with the master branch, so seems inappropriate to close this issue?

**Comment by krsna1729** [comment]
If you see thats why i removed the stale/issue label 2 days ago.
