### ISSUE TITLE
"sim" mode failing on bare metal Ubuntu 18.04 (4.15.0-76-generic)

### ISSUE THREAD

**Issue by mgeiszler** [omec-project/upf-epc#257]
**Describe the bug**
`...
Status: Downloaded newer image for golang:latest
 ---> cbf5edf38f6b`
`Step 48/60 : RUN go get github.com/golang/protobuf/protoc-gen-go@v1.4.3
 ---> Running in c550c0937f5f`
`^[[91mgo: downloading github.com/golang/protobuf v1.4.3`
`^[[0m^[[91mgo: downloading google.golang.org/protobuf v1.23.0`
`^[[0mRemoving intermediate container c550c0937f5f
 ---> 10553e7a6537`
`Step 49/60 : FROM bess-build AS go-pb
 ---> 5d2aed9d22c8`
`Step 50/60 : COPY --from=protoc-gen /go/bin/protoc-gen-go /bin
 ---> 37185347647e`
`Step 51/60 : RUN mkdir /bess_pb &&     protoc -I /usr/include -I /protobuf/         /protobuf/*.proto /protobuf/ports/*.proto         --go_out=plugins=grpc:/bess_pb`
` ---> Running in ee6a85b3e69b`
`^[[91m2021/04/14 18:33:54 WARNING: Missing 'go_package' option in "error.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.`
`See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.`

`2021/04/14 18:33:54 WARNING: Missing 'go_package' option in "bess_msg.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.`
`See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.`

`2021/04/14 18:33:54 WARNING: Missing 'go_package' option in "util_msg.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.`
`See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.`

`2021/04/14 18:33:54 WARNING: Missing 'go_package' option in "module_msg.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.`
`See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.`

`2021/04/14 18:33:54 WARNING: Missing 'go_package' option in "service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.`
`See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.`

`2021/04/14 18:33:54 WARNING: Missing 'go_package' option in "ports/port_msg.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.`
`See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.`
`...`
`Error response from daemon: Container eb0541ef9914b05c3ee576791c84defe90045f022eaeefa0550e92545e898aec is restarting, wait until the container is running`

**To Reproduce**
`tried both 3.9.3-slim and 3.9.4-slim in Dockerfile, but it didn't matter`
`Also tried "dpdk" mode using https://github.com/krsna1729/upf-epc.git repo, and same issues.`
`$ hugeadm --pool-list`
`      Size  Minimum  Current  Maximum  Default`
`   2097152     1024     1024     1024        *`
`1073741824        1        1        1`
`$ cat /proc/meminfo | grep Huge`
`AnonHugePages:      2048 kB`
`ShmemHugePages:        0 kB`
`HugePages_Total:    1024`
`HugePages_Free:     1024`
`HugePages_Rsvd:        0`
`HugePages_Surp:        0`
`Hugepagesize:       2048 kB`
`bare metal Ubuntu 18.04 (4.15.0-76-generic) with two nic cards`
DOCKER_BUILDKIT=0 ./docker_setup.sh

**Expected behavior**
`There should be 4 containers running, however only one "pause" is running and the following is constantly restarting:`
`"bessd -f -grpc-url=…"   2 minutes ago   Restarting`

**Logs**

**Additional context**
`Both the docker_setup.sh and upf.json files are only in "sim" mode.`
`Question1:  If the docker_setup.sh was only in "dpdk" mode, then what mode should be set in the upf.json file?`
`Question2:  Should docker_setup.sh ever have both "dpdk" and "sim" modes set at the same time?`

**Comment by krsna1729** [comment]
whenever you have container restarting please paste the logs of the container.

> Question1: If the docker_setup.sh was only in "dpdk" mode, then what mode should be set in the upf.json file?
Default is dpdk mode if nothing is specified in upf.json

Question2: Should docker_setup.sh ever have both "dpdk" and "sim" modes set at the same time?
> No. Only mode.

**Comment by mgeiszler** [comment]
The container log on server is empty and one cannot access the container, since it is restarting.

**Comment by krsna1729** [comment]
This should still work even when its restarting.

```
docker logs <ctr id or name>
```

regarding the go package stuff it might be related to https://github.com/omec-project/upf-epc/issues/234

**Comment by mgeiszler** [comment]
https://developers.google.com/protocol-buffers/docs/reference/go-generated#package
**Go package's import path must be provided for every .proto file (including those transitively depended upon by the .proto files being generated).** There are two ways to specify the Go import path:
**by declaring it within the .proto file, or
by declaring it on the command line when invoking protoc.**

**Where are the following files physically located, since I cannot find them?** "error.proto", "bess_msg.proto", "util_msg.proto", "module_msg.proto", "service.proto", "ports/port_msg.proto"

**What values should be provided for the following two options?**
option go_package = "example.com/project/protos/fizz";

`protoc --proto_path=src \`
`  --go_opt=Mprotos/buzz.proto=example.com/project/protos/fizz \`
`  --go_opt=Mprotos/bar.proto=example.com/project/protos/foo \`
`  protos/buzz.proto protos/bar.proto`

**Comment by krsna1729** [comment]
@mgeiszler they are here https://github.com/NetSys/bess/tree/master/protobuf

We basically only maintain patches to upstream BESS in the patches/bess folder

**Comment by krsna1729** [comment]
@mgeiszler what's the restarting status?

**Comment by mgeiszler** [comment]
@krsna1729 The restart and no docker container log issue seems to only happen in "dpdk" mode and when the "/dev/vfio/##" device has not been defined.  I am using the repo "https://github.com/krsna1729/upf-epc.git".  Could you try to reproduce, so we can at least figure out why the docker container logs are not working?
`# docker ps -a
`CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                                                                                                                 NAMES`
`1269a17d9f08   upf-epc-bess:0.3.0-dev   "bessd -f -grpc-url=…"   15 minutes ago   Created                                                                                                                                               bess`
`e2399d4a2cb1   k8s.gcr.io/pause         "/pause"                 15 minutes ago   Up 15 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:10514->10514/tcp, :::10514->10514/tcp   pause`
`docker: Error response from daemon: error gathering device information while adding custom device "/dev/vfio/48": no such file or directory.`

Using the "sim" mode does not have the restart issue nor the no docker container log issue, however it does have "insmod: not found" issue and issue "Cannot load kernel module /bin/kmod/bess.ko"

**Comment by krsna1729** [comment]
Please use better formatting.

There is no point in using my fork since its in sync with this repo.

In DPDK mode you have to provide the vfio-pci bound devices in your setup as mentioned in https://github.com/omec-project/upf-epc/issues/253

please replace /dev/vfio/XX with whatever is in your setup
