### ISSUE TITLE
bess: insmod: not found and Cannot load kernel module /bin/kmod/bess.ko

### ISSUE THREAD

**Issue by mgeiszler** [omec-project/upf-epc#258]
**Describe the bug**
docker logs bess
`...`
`I0415 16:37:31.036574     1 pmd.cc:68] 0 DPDK PMD ports have been recognized:`
`I0415 16:37:31.036687     1 vport.cc:318] vport: BESS kernel module is not loaded. Loading...`
`sh: 1: **insmod: not found**`
`W0415 16:37:31.044246     1 vport.cc:330] **Cannot load kernel module /bin/kmod/bess.ko**`
`I0415 16:37:31.044337     1 bessctl.cc:1931] Server listening on 0.0.0.0:10514`
`...`

**To Reproduce**
git clone https://github.com/krsna1729/upf-epc.git
Setup for "sim" mode (docker_setup.sh and conf/upf.json)
DOCKER_BUILDKIT=0 ./docker_setup.sh

**Expected behavior**
Expecting those files to be part of the image/container.

**Logs**
See above

**Additional context**
`# docker ps -a`
`CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS          PORTS                                                                                                                                 NAMES`
`8dd757760598   upf-epc-pfcpiface:0.3.0-dev   "/bin/pfcpiface -con…"   32 minutes ago   Up 32 minutes                                                                                                                                         bess-pfcpiface`
`1408c520dd6f   upf-epc-bess:0.3.0-dev        "bessctl http 0.0.0.…"   32 minutes ago   Up 32 minutes                                                                                                                                         bess-web`
`5ca6aa7e27cf   upf-epc-bess:0.3.0-dev        "bessd -f -grpc-url=…"   33 minutes ago   Up 33 minutes                                                                                                                                         bess`
`fc1d0d4dc878   k8s.gcr.io/pause              "/pause"                 33 minutes ago   Up 33 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:10514->10514/tcp, :::10514->10514/tcp   pause`

**Comment by krsna1729** [comment]
This only a [warning](https://github.com/NetSys/bess/blob/ae52fc5804290fc3116daf2aef52226fafcedf5d/core/drivers/vport.cc#L329-L332). We do not use bess.ko in our use case. This is required for VPort() only

```
sh: 1: **insmod: not found**
W0415 16:37:31.044246 1 vport.cc:330] **Cannot load kernel module /bin/kmod/bess.ko**
```
