### ISSUE TITLE
Generic SMF Support

### ISSUE THREAD

**Issue by infinitydon** [omec-project/upf-epc#303]
Hi,

Please can the upf-epc be used with another SMF?

I saw the following information in the installation guide:

**_UPF-EPC communicates with the CP via ZMQ. Please adjust interface.cfg accordingly._**

Does this mean that the upf-epc can only communicate to the CP (SMF) via ZMQ and not PFCP?

**Comment by krsna1729** [comment]
Before PFCP we used to support ZMQ based 4G control plane which is no longer maintained. Currently we use PFCP with both SPGW-C and SMF. Need to clean up the docs. Thanks!

**Comment by infinitydon** [comment]
Thanks @krsna1729 for the clarification..
