### ISSUE TITLE
Provide 'key' in little Endian Format in Metering Unit test case

### ISSUE THREAD

**Issue by amarsri28** [omec-project/upf-epc#307]
There is a requirement to pass 'key' in Little Endian Format rather then Big Endian to test Metering functionality.

**Comment by amarsri28** [comment]
https://github.com/omec-project/upf-epc/pull/268/commits/d934f8cf6c3a04cadb0e72f31f2fd55192d0bf20

This patch set has changes to pass 'Key' in Little Endian Format in metering unit test case.

**Comment by amarsri28** [comment]
@badhrinathpa @krsna1729

**Comment by krsna1729** [comment]
[qos_metering_support ](https://github.com/omec-project/upf-epc/tree/qos_metering_support) branch has the right format. Closing

**Comment by amarsri28** [comment]
After confirmation from Slow path that Previously(Original) held contract was OK (Big endian from Unit Test case) and this new Little Endian change is not required, Moving away from it.
Badhri already adapted changes from previous -original patch in  "qos_metering_support" branch as mentioned above.
