### ISSUE TITLE
Setting up with other core network projects.

### ISSUE THREAD

**Issue by ParkGyuhwan** [omec-project/upf-epc#360]
Hello,
I wonder if it is possible to set up with other core network projects (especially open5gs).
If possible, can you tell me how to fix the setup file for N3, N4, N6, and N9 interfacing? 
In particular, I don't know how to set the address for N4 interface in UPF-EPC.

**Comment by krsna1729** [comment]
https://github.com/omec-project/upf-epc/blob/master/INSTALL.md
https://github.com/omec-project/upf-epc/blob/master/docker_setup.sh (quick install helper)
https://github.com/omec-project/upf-epc/blob/master/conf/upf.json (app config)

**Comment by ParkGyuhwan** [comment]
Thank you for your answer. I understood in the codes that s1u & sgi in docker_setup.sh is for N3 and N6 interface, can you tell me where I should modify the address for N4 interfacing?

**Comment by krsna1729** [comment]
Thats automatically picked up. No need to set it.

**Comment by krsna1729** [comment]
Just tell in smf config file the N4 IP of UPF

**Comment by ParkGyuhwan** [comment]
Thank you for your answer. I set the environment by modifying docker_setup.sh, upf.json files of UPF-EPC and smf.yaml file of open5gs with your help. However, all packets that arrive after execution of  open5gs's smfd are directed to pdrLookupFail. If you have ever used it with open5gs, do you know what the problem is?

**Comment by krsna1729** [comment]
I have not used open5gs. You can turn on trace https://github.com/omec-project/upf-epc/blob/master/conf/upf.json#L20 and check the docker logs bess-pfcpiface to see what the issue is. Also share the screenshot of BESS UI

**Comment by ParkGyuhwan** [comment]
I'll show you the packet I already captured with tcpdump pdrLookup out 2.
The PFCP Association setup request packet fell into the pdrLookupFail gate. I don't know exactly how the rule is implemented, do you see the problem?
I'll report the bess logs later again. Thank you.
![image](https://user-images.githubusercontent.com/48062655/143098763-c80d10ee-ad69-470e-91a4-2b8bf3ca3b1a.png)

**Comment by krsna1729** [comment]
> The PFCP Association setup request packet fell into the pdrLookupFail gate

That is not how it works

**Comment by ParkGyuhwan** [comment]
> > The PFCP Association setup request packet fell into the pdrLookupFail gate
> 
> That is not how it works

That means upf-epc does not use the PFCP association setup request packet?

**Comment by krsna1729** [comment]
pdrLookup has nothing to do with association. it cares about pdrs only.

**Comment by ParkGyuhwan** [comment]
I was observing the wrong place. Somehow, I am receiving PFC Passivation setup response well now. Thank you.
Another project's smf reports that "F-TEID allocation/release not supported with peer," so I wonder if upf-epc supports F-TEID or if I'm using it incorrectly.
And can you tell me in little bit more detail how to set up the item in docker_setup.sh? :
> Static IP addresses of the neighbors of gateway interface (n-s1u n-sgi)
> IPv4 route table entries in cidr format per port ({r-s1u} {r-sgi})

**Comment by krsna1729** [comment]
> Another project's smf reports that "F-TEID allocation/release not supported with peer," so I wonder if upf-epc supports F-TEID or if I'm using it incorrectly.

cc @badhrinathpa @thakurajayL 

> And can you tell me in little bit more detail how to set up the item in docker_setup.sh?

basically on each direction what is your router IP which is used as next hop. If you use a packet generator, it will be the IP/MAC of that entity.

**Comment by ParkGyuhwan** [comment]
I have a question, just hearing the name UPF-EPC sounds like a 4G EPC network, is it designed to be compatible with the 5G core network?

**Comment by krsna1729** [comment]
It should have been named `upf`. It supports both 4G and 5G control plane via PFCP.

**Comment by ccascone** [comment]
+1 for renaming the repo. GitHub actually handles that very well, automatically handling redirection for http and git commands: https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by ParkGyuhwan** [comment]
> > 
> 
> cc @badhrinathpa

Can you tell me whether upf-epc supports F-TEID or only TEID?
Thanks.

**Comment by infinitydon** [comment]
@ParkGyuhwan - Were you able to get this to work with Open5gs SMF?

**Comment by ParkGyuhwan** [comment]
@infinitydon No, the UP function feature (FTUP) in the PFCP association setup request/response is different, so I gave up setting up with Open5gs for now.
