### ISSUE TITLE
Refactor source structure to follow BESS sample_plugin

### ISSUE THREAD

**Issue by krsna1729** [omec-project/upf-epc#4]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently we structure the module source code around BESS's core source code. Instead should we refactor it to follow [sample_plugin](https://github.com/NetSys/bess/tree/master/sample_plugin).

**Describe alternatives you've considered**
We can continue the way we are doing it today

**Additional context**
No

**Comment by ajamshed** [comment]
Thanks. Will look into this further.

**Comment by ajamshed** [comment]
This will also help in removing soft linked file as mentioned in PR #11.

**Comment by krsna1729** [comment]
backburner but need to do

**Comment by ajamshed** [comment]
Leaving a comment to keep this issue alive.
