### ISSUE TITLE
Setting up with Mellanox NIC

### ISSUE THREAD

**Issue by ParkGyuhwan** [omec-project/upf-epc#401]
Hello. Thanks to your help, the setup UPF-EPC with Intel NIC was successful. 
Now, I would like to use Mellanox Connectx-5 as a network interface for UPF-EPC. 
However, the Mellanox device does not use 'dpdk-devbind' or vfio. The 'docker_setup.sh' in dpdk mode of UPF-EPC requires a DEVICES variable bound to vfio. 
How should I set up to use the mellanox NIC?
Thanks.

**Comment by krsna1729** [comment]
I have not tried this, so I would say try with simple dpdk app like testpmd initially on the host, then in a container. Then you apply the findings to docker_setup.sh.

**Comment by ParkGyuhwan** [comment]
Mellanox said that any application attempt use VFIO through DPDK is not support on Mellanox's NIC. SR-IOV can be used for it, but its performance does not look good. Thanks for answer.

**Comment by ParkGyuhwan** [comment]
Have you ever done CPU affinity and utilization analysis in UPF-EPC? I'm not sure which method to use for this project using Go language, DPDK, and Docker.

**Comment by krsna1729** [comment]
Again in docker_setup.sh you can customize cpuset, cpushares etc in docker commandline for each container. The bessd container takes argument `workers` in `upf.json` to spin up worker (polling) threads. From linux perspective they are 100% utilized, so application level statistics can be checked using `bessctl monitor tc`

**Comment by ParkGyuhwan** [comment]
Is there a document of BESS that explains `tc`? It's hard to figure out what each `!port_leaf` means. I wonder if I can know the worker allocation in module units. and Can I also figure out the worker distribution in module units?

**Comment by krsna1729** [comment]
https://github.com/NetSys/bess/wiki/The-BESS-Scheduler
