### ISSUE TITLE
What is the correct size of sequence number in the GTPv1 header?

### ISSUE THREAD

**Issue by ajamshed** [omec-project/upf-epc#6]
**Describe the bug**
Did some tests with Spirent packet generator. The GTP packets (with sequence numbers) are using up 4 B to store sequence numbers (instead of 2 bytes). We need to verify this. A PR (#8) has been submitted to fix this issue. Not sure whether this is a correct patch.

**To Reproduce**
Run Spirent Landslide gold testcase that was created by the Spirent team for the Intel TSR group.

**Expected behavior**
See above.

**Logs**
PCAP files may be uploaded soon.

**Additional context**
The original ngic-rtc code also reserves 4B field to store sequence numbers. Someone needs to verify the field size from the 3GPP specs as well.

**Comment by thakurajayL** [comment]
You mean GTPv2 ? or GTPU ?

**Comment by ajamshed** [comment]
GTPv1 over fast path

**Comment by thakurajayL** [comment]
29.281 spec tells the following,

Sequence Number: If Sequence Number field is used for G-PDUs (T-PDUs+headers), an increasing sequence number for T-PDUs is transmitted via GTP-U tunnels, when transmission order must be preserved. For Supported Extension Headers Notification and Error Indication messages, the Sequence Number shall be ignored by the receiver, even though the S flag is set to '1'.


As per GTPU header format section 5.1 of 29.281, sequence number is 2 byte in length.

**Comment by ajamshed** [comment]
Thanks @thakurajayL. We also made the same observation. Can you please help us out a bit further? The current code of ngic-rtc has `gtpu_hdr` definition where seqnb spans 4B. Can you make some edits in gtpu.h?:

https://github.com/omec-project/ngic-rtc/blob/67bc9d42b5700e969b6546b122452ea498222c3d/dp/gtpu.h#L24-L55

https://github.com/omec-project/ngic-rtc/blob/67bc9d42b5700e969b6546b122452ea498222c3d/dp/gtpu.c#L30-L178

And then see if your tests with with GTP sequence numbers work. Thanks!

**Comment by thakurajayL** [comment]
Looks like i need to set GTPU_SEQNB_IN & GTPU_SEQNUM_OUT in the configuration. Currently we may not be having this setting...I will definitely look into this as soon as I get the hands on the setup.

**Comment by thakurajayL** [comment]
Need some more time.
