### ISSUE TITLE
Allow eNB and s1u in a same subnet

### ISSUE THREAD

**Issue by hyunsun** [omec-project/upf-epc#80]
It would be great if eNB and s1u interface of UPF can be in a same subnet.

**Comment by thakurajayL** [comment]
Why current UPF does not allow it ? Any specific reason ?

**Comment by krsna1729** [comment]
@thakurajayL PR welcome :)

**Comment by krsna1729** [comment]
Need an L2 stack. Neighbor table and buffering capability need to be implemented. For unknown endpoints we could either - 

1. drop and probe
2. send to kernel and let it deal

Also need to implement timeout in fastpath to account for dynamic environment.
